version: '3.5'
services:
  event-service-rest:
    image: 'openjdk:8-alpine'
    container_name: 'event-service-rest'
    ports:
      - "8080:8080"
    volumes:
      - "./event-service-rest/target/event-service-rest-1.0.jar:/app.jar"
    command: "java -jar app.jar"
    environment:
      - spring.profiles.active=kafka
    networks:
      - msg-net
  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - msg-net
  kafka:
    image: 'bitnami/kafka:3.2'
    container_name: 'kafka-server'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - msg-net
  activemq:
    image: 'rmohr/activemq:5.15.9-alpine'
    container_name: 'activemq-server'
    ports:
      - '61616:61616'
      - '8161:8161'
    networks:
      - msg-net
  rabbitmq:
    image: 'bitnami/rabbitmq:3.10'
    container_name: 'rabbitmq-server'
    ports:
      - '15672:15672'
    networks:
      - msg-net
networks:
  msg-net:
    driver: bridge